site_name: Bevy

theme:
  name: material

plugins:
  - mkdocstrings

nav:
  - Getting Started: index.md
  - Quick Start: ../BEVY_QUICKSTART.md
  - API Reference: api.md
  - Migration Guide: migration.md
