name: Release Bevy to PyPI
on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.12
      uses: actions/setup-python@v1
      with:
        python-version: "3.12"
    - name: Install injectors.py
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry config virtualenvs.in-project true
    - name: Build and publish
      env:
        PYPI_USERNAME: __token__
        PYPI_PASSWORD: ${{ secrets.PYPI_TOKEN }}
      run: |
        poetry publish --build --username $PYPI_USERNAME --password $PYPI_PASSWORD
